# Generated by Django 5.2.6 on 2025-09-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.BooleanField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Enable'),
        ),
    ]
