# Generated by Django 5.2.6 on 2025-09-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.ImageField(upload_to='links/icons', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.BooleanField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Enable', verbose_name='status'),
        ),
    ]
