# Generated by Django 5.2.6 on 2025-09-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_link_created_at_alter_link_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
    ]
