# Generated by Django 5.2.6 on 2025-10-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_alter_link_status_alter_link_user_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='links/icons', verbose_name='icon'),
        ),
    ]
